# itk-version: 3.2.1
services:
  phpfpm:
    environment:
      - PHP_SENDMAIL_PATH=/usr/sbin/sendmail -S mail:1025

  nginx:
    labels:
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.middlewares=ITKBasicAuth@file"


